export const eightBallSentencesEng = [
	// Positive
	'As I see it, yes',
	'It is certain',
	'Yes, definitely',
	'You may rely on it',
	'Without a doubt',
	'Most likely',
	'Yes',
	'Seems so',
	'There\'s a world where it\'s possible',
	'Yes, if you believe in it very hard',
	'I believe in it like hell',
	'It\'s 99% sure',
	'Seems conceivable to me',
	// Indecisive
	'It\'s better that you don\'t know right now',
	'Perhaps...',
	'Even I can\'t give you the answer to that question',
	'I prefer really not to speak. If I speak, I\'m in big trouble. And I don\t want to be in big trouble',
	'I\'d say it\'s a 50/50',
	// Negative
	'No way',
	'Well, yes but actually no',
	'Not even in your dreams',
	'I don\t think so',
	'Screw you',
	'That\'s a no.',
	'Unlikely',
	'Don\'t count on it',
	'Impossible',
	'Not impossible but you\d be moke likely to win the lottery',
	'It could seem strange but the answer is no',
	'I wouldn\'t bet on that',
	'Nope. Not happening',
]

export const eightBallSentencesFr = [
	// Positif
	'D\'après moi oui',
	'C\'est certain',
	'Oui absolument',
	'Tu peux compter là dessus',
	'Sans aucun doute',
	'Très probable',
	'Oui.',
	'Il me semble bien',
	'Y\'a un monde où c\'est possible',
	'Oui, si tu y crois très fort',
	'J\'y crois dur comme fer',
	'C\'est sûr à 99%',
	'Ça me semble plausible',
	// Indécis
	'Mieux vaut pas que tu saches pour le moment',
	'Peut-être...',
	'Même moi je ne saurais pas répondre à ça',
	'Je préfère vraiment ne rien dire. Si je parle je vais avoir de gros problèmes. Et je ne veux pas avoir de gros problèmes',
	'Il y a 50% de chances',
	// Négatif
	'Non, pas moyen',
	'Oui... Euh en fait non, vraiment pas',
	'Même pas en rêve',
	'J\'y crois pas trop',
	'Va te faire foutre',
	'C\'est non.',
	'Peu probable',
	'N\'y compte pas',
	'Impossible',
	'Pas impossible mais t\aurais plus de chance de gagner au loto',
	'Ça peut sembler étrange mais la réponse est non',
	'Je parierais pas là-dessus',
	'Non c\'est mort',
]