export const eightBallSentencesEng = [
	'As I see it, yes',
	'Ask again later',
	'Better not tell you now',
	'Cannot predict now',
	'Concentrate and ask again',
	'Don\'t count on it',
	'It is certain',
	'It is decidedly so',
	'Most likely',
	'My reply is no',
	'My sources say no',
	'Outlook good',
	'Outlook not so good',
	'Reply hazy try again',
	'Signs point to yes',
	'Very doubtful',
	'Without a doubt',
	'Yes',
	'Yes, definitely',
	'You may rely on it',
]

export const eightBallSentencesFr = [
	'Essaye plus tard',
	'Essaye encore',
	'Pas d\'avis',
	'C\'est ton destin',
	'Le sort en est jeté',
	'Une chance sur deux',
	'Repose ta question',
	'D\'après moi oui',
	'C\'est certain',
	'Oui absolument',
	'Tu peux compter dessus',
	'Sans aucun doute',
	'Très probable',
	'Oui',
	'C\'est bien parti',
	'C\'est non',
	'Peu probable',
	'Faut pas rêver',
	'N\'y compte pas',
	'Impossible',
]